enabled: true

excluded_blocks:
  - LAVA
  - STATIONARY_LAVA
  - WATER
  - STATIONARY_WATER
  - CACTUS
  - WEB
  - VINE
  - LEAVES
  - LEAVES_2


worlds:
  world:
    enabled: true
    shape: circle
    radius:
      x: 100
      z: 100
    center:
      x: 0
      z: 0
    handled_types:
     - FIRSTJOIN
     - RESPAWN
     - BEDRESPAWN
     - FIRSTWORLDSPAWN
     - JOIN